---
title: TogetherCBT
slug: aldao
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# TogetherCBT

<span style="color:green">
**TogetherCBT is currently seeking research assistants**
</span>


***

## Lab Description:

[Together CBT](https://www.togethercbt.com/) is a private practice specializing in cognitive behavioral therapy (CBT) for anxiety, stress, OCD, sleep, ADHD, depression, relationship issues, and related conditions. It is led by licensed clinical psychologists Dr. Amelia Aldao and Dr. Henri-Lee Stalk. We are a training clinic and we supervise and train clinical psychology students and post-doctoral fellows on the assessment and treatment of emotional and behavioral health disorders. We have a team of 10 providers, including staff psychologists, post-doctoral therapists, and psychology graduate student therapists. 

We are excited to bring in undergraduate research assistants looking to get hands-on experience with cognitive behavioral therapy. Together CBT offers training and mentorship to undergraduate students who are keen to learn about applying psychology research in private practice, creating value as a psychologist for audiences across media platforms, and disseminating and implementing evidence based behavioral science.

Dr. Aldao and Dr. Stalk are also management consultants who support companies with using evidence-based behavioral science principles and research to improve their product and service offerings. They both spent a couple of years working in consulting, including for one of the “big 3” firms, Boston Consulting Group.

To learn more about the research assistant opportunities we offer at Together CBT, please visit our [website](https://www.togethercbt.com/undergrad).

## Contact Information:

If you are interested in applying for a RA position, please email us your CV and a short description of your interest in the lab (100-200 words).

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Amelia Aldao","Henri-Lee Stalk"),
                   Role = c("Founder & Director","Clinical Director"),
                   Email = c("draldao@togethercbt.com","drhenrileestalk@gmail.com"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

