---
title: Developmental Cognitive Neuroscience Lab 
slug: amso
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Developmental Cognitive Neuroscience Lab 

<span style="color:green">
**The Developmental Cognitive Neuroscience Lab is currently seeking research assistants**
</span>

***

## Description of Research Projects: 
Current projects are exploring caregiver-infant dyadic interactions through multiple lenses. We are working with several datasets capturing caregiver-infant interactions via video recordings and applying 2 distinct behavioral coding schemes to extract data points of interests. Your role as an RA would entail coding of these videos using the software Datavyu. Here, you would be exposed to the naturalistic behaviors of caregivers and their infants throughout the first year of life and gain experience with common tools used to process and analyze observational data in psychology. Additionally, you will be part of lab meetings and conversations discussing a board range of topics our lab aims to address in developmental cognitive neuroscience/psych. 

## RA Requirements:
You are available to work as a research assistant in our lab for 2 or more full semesters (Fall and Spring). 
You are able and willing to commit a minimum of 10hrs/week to the lab
Are majoring or minoring in a related field and have already taken at least 2 relevant courses in the past (psych, neuro, development, cogsci, other related topics)
Interested in working with younger populations (i.e. infants, toddlers, children) and their families 

## RA Preferences (aka not hard requirements):
We are looking to hire 1 work-study student, so please do let us know if you have work-study available
Fluent in Spanish 
Great overall communication skills

## Application Process: 
If you are interested, please ensure you meet the requirements listed above and email Claudia at ce2435@columbia.edu with the following information. 
School, Major, and school year
Number of hours available per week 
Do you have work-study?
Are you fluent in Spanish?
Brief description of current career goals and research interests. 
Attach Resume/CV inclusive of any experience that may have provided you with skills that may be useful for this position. Note, this is not exclusive to research experience and relevant research experience is not required. 

*If you have further questions, please feel free to contact Claudia at ce2435@columbia.edu. 
```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Monique Gilmore"),
                   Role = c("Research Staff Assistant"),
                   Email = c("mgg2163@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

