---
title: Dynamic Perception and Memory Lab
slug: baldassano
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Dynamic Perception and Memory Lab

<span style="color:green">
**The Dynamic Perception and Memory Lab is currently seeking research assistants**
</span>

<div class="video-box">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/RfsDyBOnZ_g"></iframe>
</div>

***

The Dynamic Perception and Memory Lab studies how we can understand and remember the complex world of our everyday lives. Through experiments using narratives, movies, and virtual reality, we investigate how experiences are divided into events, summarized, associated, and recalled. Our current projects are specifically focused on how our prior knowledge about the temporal and spatial structure of the world influences our construction of mental representations.

Using neuroimaging tools (primarily functional MRI), we can build models of how neural representations vary across stimuli and across people. We employ both hypothesis-driven and data-driven approaches based on approaches from modern machine learning, which allow us to ask new kinds of questions about how brain regions respond to the world and interact with each other.

We are currently recruiting volunteer RAs to perform tasks such as designing and annotating stimuli, transcribing or coding verbal recall data, preparing presentation materials, and (for more experienced RAs) running experiments with human subjects. We expect RAs to commit at least 5 hours a week for 2 semesters. If interested, please email Alexandra Reblando at <ColumbiaDPML@gmail.com> with your resume, a short description about why you are interested in working in the lab, and your availability.

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Alexandra Reblando"),
                   Role = c("Lab Manager"),
                   Email = c("ColumbiaDPML@gmail.com"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

