---
title: The Couples Lab
slug: couples
---

# The Couples Lab

<span style="color:red">
**The Couples Lab is not actively seeking research assistants**
</span>

***

## Research Projects

In the Columbia Couples Lab we study dyadic processes (i.e. interactions between two individuals), particularly in health-relevant contexts. Our primary lines of research include how people co-experience stress, how people support each other through adversity, and how people cope with stress (e.g., do they co-ruminate?).

We aim to understand how social relationships influence people's functioning, especially during times of stress, as well as how the relationship itself functions during these adverse experiences. We do so by studying romantic couples, parent/child dyads, friend pairs, and unacquainted strangers; for example, some current research examines social interactions between individuals who have never met but experience the same stressful event and other recent work looks at how romantic couples experienced daily life together during the COVID-19 pandemic. 

We use intensive repeated-measures designs to study dyad members and their interactions and to explore how daily transactions affect processes such as relationship satisfaction, self-regulation, self-efficacy, and overall psychological, physical, and physiological functioning. We incorporate multiple methodologies in our studies, using both psychophysiological methods and naturalistic self-report approaches. Finally, we work with a range of statistical and methodological tools to understand these processes, including multilevel models, structural equation models, and dynamical systems models that are suitable for the study of change processes in individuals and dyads, both between and within persons.

## Contact Information

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Ana DiGiovanni"),
                   Role = c("PhD Student"),
                   Email = c("amd2323@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

