---
title: Social Relations Lab
slug: downey
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Social Relations Lab

<span style="color:red">
**The Social Relations Lab is not currently seeking research assistants**
</span>

***

Led by Geraldine Downey, the Social Relations Lab studies several topics that allow us to discern the effects of situational factors on the individual, and the effects of individuals on their environment and their immediate situation.  One of the lab’s principal focuses has been rejection sensitivity, which is the disposition to anxiously expect, readily perceive, and intensely react to rejection.  

Current research studies cognitive, affective, and behavioral outcomes associated with disclosure of one’s criminal record.  We are also interested in development, behavior, and punishment with respect to both youth and aging populations.  Finally, we are interested in drugs and behavior — studying, most recently, cognitive functioning of people who use cocaine.  

Our research teams reflect populations that are affected by our work — something we value highly.  We collaborate with the Center for Justice at Columbia, of which Geraldine is the Director — which is committed to reducing the nation’s reliance on incarceration and advancing alternative approaches to safety and justice through education, interdisciplinary research, and policy. 


## Contact Information

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Mike Naft"),
                   Role = c("Graduate Student"),
                   Email = c("srlmgr1@gmail.com"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

