---
title: Nurture Science Program
slug: dumitriu
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Nurture Science Program

<span style="color:green">
**The NSP is currently seeking research assistants**
</span>


***

## Lab Description:

The Nurture Science Program (NSP), directed by Dr. Dani Dumitriu, is dedicated to understanding the mechanisms by which emotional connection emerges between mothers and infants, and to disseminate tools and practices that foster parent-child emotional connection. In the fall of 2022, NSP will spearhead a randomized controlled trial (RCT) into the Well Baby Nursery at the Morgan Stanley Children's Hospital to evaluate the effectiveness of the Family Nurture Intervention to help strengthen emotional connection between babies and parents.
 
We are currently able to add research assistants to our team to help with participant-facing or computer-based activities, such as participant recruitment, data collection, data analysis, video coding (training will be provided), and more. Our upcoming RCT also involves participant-facing research activities over zoom, including interfacing with mothers and babies to disseminate education about newborn baby care and conducting periodic follow-up visits. 

## Contact Information:

To apply for a volunteer research assistant position, please email your CV, your anticipated weekly availability, and a brief message describing your interest in the project to Andréane Lavallée (al4196@cumc.columbia.edu). For more information, please visit our [lab website](https://nurturescienceprogram.org) or contact us!

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Andréane Lavallée","Ginger Atwood"),
                   Role = c("Postdoctoral Research Fellow","Research Coordinator"),
                   Email = c("al4196@cumc.columbia.edu","ga2608@cumc.columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

