---
title: The Social Cognitive and Neural Sciences Lab
slug: freeman
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Social Cognitive and Neural Sciences Lab

<span style="color:red">
**The Freeman Lab is not currently seeking research assistants**
</span>


***

## Lab Description:

The Social Cognitive and Neural Sciences Lab at Columbia University investigates the cognitive and neurobiological mechanisms that allow people to make sense of their social worlds. We integrate insights and techniques across social psychology, cognitive neuroscience, affective science, and vision science.

Our research can be organized around 4 main themes: 

### Person Perception:

What processes do we use to make social meaning of a person’s face? A brief glance can reveal the social groups to which a person belongs, the emotions they feel, and even the personality traits they likely possess, but how? How does our own social knowledge and past experiences shape perceptions?

### Social Vision: 

Our research explores how what we think and believe about the social world can influence the visual “reality” we see before our eyes, and it identifies the neural mechanisms involved in these social cognitive impacts on visual perception.

### Stereotyping and Bias: 

How are stereotypes and less conscious forms of bias learned and maintained in the brain, and how can they be reduced or even eliminated? What are the effects of the stereotypes we implicitly hold on perception and behavior?

### Emotion: 

How do we perceive other people’s emotions, and how is this shaped by our own understanding of emotion and our affective experiences? Conversely, how are our affective experiences and understanding of emotion affected by perceptions of others?

For more concrete examples of our research, please visit our webpage for recent [publications](https://www.freemanlab.org/publications). 


## Contact Information:

To apply for a research assistant position, please visit our webpage and fill out our [application](https://www.freemanlab.org/join)
