---
title: Social and Moral Cognition Lab
slug: heiphetz
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# Social and Moral Cognition Lab

<span style="color:red">
**The Social and Moral Cognition Lab is not actively seeking research assistants**
</span>

<div class="video-box">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/tgbNymZ7vqY"></iframe>
</div>

***

## Research Questions

***

In the Social and Moral Cognition (SAMC) Lab, we are interested in how children and adults understand their social world. This is a big question, and many topics fit under this broad umbrella! Below are some topics we are currently investigating, and some of the questions we are most fascinated by:

### The development of social preferences

How do children and adults reason about and interact with people who are different from them? Many psychologists have investigated this question in the domains of race and gender. In contrast, most of the work in our lab focuses on social preferences based on beliefs such as religion and morality, which may function differently from other domains for several reasons. Because beliefs are not perceptually salient (it's not always possible to tell what someone thinks just by looking at them), it may be difficult for children to determine who is like them.

### Religious cognition

Religious beliefs and practices are an important aspect of many people's lives, yet how individuals understand religious ideas remain under-studied in psychology. Our work shows that children and adults distinguish religious beliefs from other mental states, such as factual beliefs and opinions.


### Moral cognition

People's moral viewpoints influence many aspects of their lives, including whom they choose to befriend, avoid, reward, and punish. Our work in this area investigates several interrelated topics, including children's understanding of morality and the relationship between moral beliefs and other types of beliefs (e.g., religious, factual, political). Another line of our work investigates how people judge moral beliefs to be a central aspect of their own (and others’) identity.

### Judgments of the criminal justice system

Currently, over 2.3 million American adults are behind bars. The vast majority of these individuals will return to the world outside the prison walls. What do these individuals experience before, during, and after their incarceration? Answering this question sheds light on many of the topics studied in our lab. For example, incarceration disproportionately affects African American communities, and currently and formerly incarcerated individuals face stigma in domains such as employment and housing. Therefore, work on intergroup attitudes can provide a helpful lens through which to understand some aspects of incarceration, and studying incarceration can move the study of intergroup attitudes into a domain that is relatively new for psychologists.

## Contact Info

***


```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Sophie Charles"),
                   Role = c("Lab Manager"),
                   Email = c("snc2123@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

