---
title: Motivational and Social Cognition
slug: higgins
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Motivational and Social Cognition

<span style="color:red">
**The Motivational and Social Cognition Lab is not currently seeking research assistants**
</span>

***

## Research Projects

In the Higgins Lab, we study the motivational underpinnings of perceptions, judgments, decisions, and behaviors in a wide range of contexts. Ongoing projects in our lab explore how different fundamental motives influence how people relate to each other, navigate their social worlds, and pursue their goals. We embrace a motivated cognition framework in pursuing both basic and applied research questions, such as:

### Interpersonal Processes

What makes strangers ‘click’? What does it mean to have ‘merged minds’ with a close relationship partner? What are the motivational processes underlying the development and maintenance of romantic relationships? Can a ‘shared reality’ with a close partner change our physical perceptions of the world around us? How do we effectively provide and receive social support?

### Goal Pursuit Processes

How do different motivational orientations relate to the process of goal pursuit? Do people who are primarily concerned with achieving gains pursue their goals differently from people who are primarily concerned with ensuring against losses? How do these different groups of people evaluate the success or failure of these pursuits?

### Motivational Effectiveness

What makes people effective at what they do? How do different primary motives work together to promote a broader sense of well-being and “the good life”?

## Working in the Lab
Research assistants work closely with graduate students and help with different stages of projects, including background literature searches, research design, participant recruitment, data collection, analysis and interpretation, thereby acquiring a variety of methodological skills.
  
*The Higgins Lab does not currently have any open research assistant positions, but such positions may open up over the course of the coming academic year. If so, positions are typically volunteer-based roles with a 10+ hour/week commitment for at least 2 semesters. These positions also offer the possibility of conducting Supervised Independent Research (for credit) in the future, after completing at least one semester of volunteer work.*

Any interested students should contact cuhigginslab@gmail.com and attach your resume, unofficial transcript, and a brief (~250-word) statement of interest. Alternatively, read through the People section of our lab website and directly email the graduate student whose work interests you most, with the same application materials: https://cuhigginslab.com/people 

Applicants are evaluated on a rolling basis.

## Contact Information

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Emily Nakkawita"),
                   Role = c("Graduate Student"),
                   Email = c("cuhigginslab@gmail.com"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

