---
title: Visual Inference Lab
slug: kriegeskorte
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Visual Inference Lab

<span style="color:green">
**The Visual Inference Lab is currently seeking research assistants**
</span>


***

# Lab description

The Visual Inference Lab studies the brain information processing that enables visual perception, object recognition, and scene understanding. A core goal of the lab is to build neural network models to predict human and animal performance in visual tasks and the concomitant brain activity. Our research involves neural network modeling, measurement of behavior and brain activity in human and nonhuman primates, and development of statistical analysis and visualization techniques. Additional information about our research is available at our [lab website](https://kriegeskortelab.zuckermaninstitute.columbia.edu/)

# Contact Information

We intend to recruit at least one RA (possibly two) for a neuroimaging (functional MRI) project on the neural mechanism of human face perception. RAs will be primarily trained to conduct fMRI experiments and would participate in data collection, preprocessing, and analysis. If interested, RAs can also learn about visual computational modeling and model selection methods. RAs are welcome to participate in lab meetings, journal clubs, and other events.

The lab accepts applications from students intending to enroll in research for course credit (e.g. PSYC UN3950 or equivalent). We require a commitment of 10-12 hours per week at minimum for at least one semester. Prior programming experience in Python is especially beneficial for all applicants, and is a requirement for students interested in working on computational projects.

Interested students should complete the inquiry form listed on our website (listed under Participate -> Prospective Research Assistants). Please contact Jennifer Lieberman (jl5401@columbia.edu) and cc Wenxuan Guo (wg2361@columbia.edu) and Tal Golan (tal.golan@columbia.edu) with any questions.

```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Jennifer Lieberman",
                                  "Wenxuan Guo",
                                  "Tal Golan"),
                   Role = c("Lab Manager",
                            "Grad Student",
                            "Post-Doc"),
                   Email = c("jl5401@columbia.edu",
                             "wg2361@columbia.edu",
                             "tal.golan@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

