---
title: Computational Behavioral Science Lab
slug: matz
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Computational Behavioral Science Lab

<span style="color:green">
**The Computational Behavioral Science Lab is currently seeking research assistants**
</span>

<div class="video-box">
  <iframe class="responsive-iframe" src="https://drive.google.com/file/d/1he_ag4xRGsx3qsWAtYCbGY8VmvDPaegK/preview"></iframe>
</div>

***

## Research Projects

At the Computational Behavioral Science Lab headed by Sandra Matz at Columbia Business School, we take a Big Data approach to studying human behavior in a variety of life domains. We combine methodologies from psychology and data science – including machine learning, experimental designs, online surveys, and field studies – to explore the relationship between people’s psychological characteristics (e.g. their personality) and the digital footprints they leave with every step they take in the digital environment (e.g. their Facebook Likes or their location tracking). 

More specifically, our research focuses on the following three questions: 

1. What can people’s digital footprints tell us about their socio-psychological characteristics?

2. What can people’s digital footprints tell us about the real-life consequences of their unique psychological characteristics?

3. How can insights extracted from people’s digital footprints help individuals make better decisions?


## Contact Information

If you want to get involved with cutting edge research at the intersection of behavioral science, technology, and data science, join the Computational Behavioral Science Lab! RAs will be working closely with various members of the laboratory including other RAs, PhD students, and postdoctoral fellows. You may be involved in a variety of different tasks, including literature surveys, study design, data collection and data analysis. To apply for a research assistant position, please reach out to us at hp2500@columbia.edu. Please be sure to include a CV, recent unofficial transcript, and short description of your interest in the lab (100-200 words).


```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Sandra Matz"),
                   Role = c("PI"),
                   Email = c("hp2500@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

