---
title: The Learning Lab
slug: shohamy
---

```{css, echo = FALSE}
.video-box {
  position: relative;
  overflow: hidden;
  width: 100%;
  padding-top: 56.25%; /* 16:9 Aspect Ratio (divide 9 by 16 = 0.5625) */
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
```

# The Learning Lab

<span style="color:green">
**The Learning Lab is currently seeking research assistants**
</span>

***

<div class="video-box">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/0xIn71ffSKY"></iframe>
</div>

***

<div class="video-box">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/XPUxmgPyTt0"></iframe>
</div>


***

## Research Projects

Our research is focused on the intersection between learning, memory and decision making. We are interested in characterizing when and how different brain systems for learning interact and whether this interaction is competitive or cooperative. 

We focus on two main brain systems for learning - one in the striatum and the other in the hippocampus. Traditionally, the striatum and hippocampus were thought to support independent and distinct learning systems. We have demonstrated that there is cross-talk between these systems during learning, raising questions about the nature of this interaction and its significance for learning and decision making. We are now investigating how this cross-talk is impacted by several key factors, including: motivation and feedback, social context of learning, aging, and genetic differences between learners.
We study several populations, including: undergrads, Parkinson's Disease patients, older adults (50 - 85 years old), children, and adolescents. 

For more information, please see our lab website: http://shohamylab.psych.columbia.edu/

Any future position will be responsible for a wide-range of tasks, including: recruitment, running subjects, and data entry. RA's would also be invited to attend lab meetings. With experience, qualified RAs may be eligible to take on projects with greater responsibility and autonomy.
Ideally, RAs will commit to working 8 - 10 hours/week for a minimum of two semesters.

## Full Time Position Available

The Learning Lab at Columbia University is also seeking a full-time research assistant beginning as early as Summer 2022. The research study uses behavioral modeling and functional brain imaging to investigate how the human brain learns abstract concepts and applies them to new cases. The ideal candidate would have an undergraduate degree (BA or equivalent) and significant experience with at least one of the following: running research studies with human subjects, statistical analysis, and/or computer programming. If you think your background would be a good fit, please complete the online application. Please send any questions to Dr. Daniel Kimmel at dkimmel@columbia.edu. Thank you for your interest.


## Contact Information


```{r, echo = F}
library(kableExtra)
options(kableExtra.html.bsTable = TRUE)
contact <- data.frame(Contact = c("Eileen Hartneet",
                                  "Alice Xue"),
                   Role = c("Lab Manager",
                            "Lab Manager"),
                   Email = c("eah2134@columbia.edu",
                             "amx2002@columbia.edu"))
contact %>%
  kbl() %>%
  kable_material(c("striped","hover"))
                   
                   
```

